### ISSUE TITLE
Subtask: Create a new project on google cloud console

### ISSUE THREAD

**Issue by AsiaJoyG** [the-silver-snakesss/gracessshopper#14]
subtask of #3
- [x] Obtain client id/ secret/ callback 
- [x] create secrets.js and add to .gitignore
- [x] in secrets.js load in as process.env.NAME
