### ISSUE TITLE
Subtask: Create a Friend Model using Sequelize

### ISSUE THREAD

**Issue by ageismar** [the-silver-snakesss/gracessshopper#16]
Subtask of #4

- [x] Define Model called Friend
   - All fields are required 
   - [x] Name column (STRING)
   - [x] Info column (TEXT)
   - [x] Likes column (TEXT)
   - [x] Activities Column (TEXT)
   - [x] Price Column (FLOAT WITH 2 DECIMAL)
   - [x] Instock column (BOOLEAN)
   - [x] img
