### ISSUE TITLE
Subtask: Action/Reducer/Thunk Redux for User Page

### ISSUE THREAD

**Issue by AsiaJoyG** [the-silver-snakesss/gracessshopper#21]
subtask of #3
- [ ] sub reducer for User 
- [ ] action type for Get User
- [ ] case for Get User
- [ ] thunk for User
