### ISSUE TITLE
Subtask: Checkout Button Functionality #10

### ISSUE THREAD

**Issue by gURLmeetsCode** [the-silver-snakesss/gracessshopper#25]
- [x] - Should be clickable 
- [x] - should navigate checkout view
- [x] - should have associated routes Ex.('/checkout')
- [x] - should dispatch associated thunks
