### ISSUE TITLE
Subtask: Integrate payment API #10

### ISSUE THREAD

**Issue by gURLmeetsCode** [the-silver-snakesss/gracessshopper#26]
- [x] - checkout API documentation: https://developers.braintreepayments.com/start/overview
- [x] - Set up JS SDK
- [x] - Test API with dummy data
