### ISSUE TITLE
Subtask: Checkout routes #10

### ISSUE THREAD

**Issue by gURLmeetsCode** [the-silver-snakesss/gracessshopper#27]
Server side: 
- [x] -  PUT route in express / UPDATE method in sequelize
- [x] - DELETE route in express / DESTROY method in sequelize
- [x] - POST route in express / CREATE method in sequelize
