### ISSUE TITLE
Subtask: There should see a button on a single selected friend view (Front end)

### ISSUE THREAD

**Issue by blydiet** [the-silver-snakesss/gracessshopper#29]
- [x] User should be able to see a navbar with Home, shop and a shopping cart
- [x] User should be able to see an image of selected Friend
- [x] User should be able to see an Add to cart button underneath the selected Friend 
- [x] User should be able to see an info field with information about a friend
- [ ] User should be able to see the number of likes that a friend has 
- [ ] User should be able to see the activities that a friend has 
- [ ] User should be able to see the price of a friend
