### ISSUE TITLE
User Story: User can login under their username with password

### ISSUE THREAD

**Issue by AsiaJoyG** [the-silver-snakesss/gracessshopper#3]
- [x] Client Id/ secret/ call back for google Oauth (#14 )
- [x] model defined as user (sql) (#15 )
- [x] get request loads user info (express) (#18 )
- [x] user home page component  (react) (#19 )
- [x] user action types/user reducer/ thunk (redux) (#21 )

**Comment by blydiet** [comment]
[ ]
