### ISSUE TITLE
Subtask: Create add Cart Component

### ISSUE THREAD

**Issue by blydiet** [the-silver-snakesss/gracessshopper#30]
#7
- [x] Create to add to cart component 
- [x] Component should have a navbar with home, shop and the  shopping cart 
- [x] As a user you should see text that says 'You Added' 
- [ ] As a user you should see the name of the friend that you just added
- [ ] As a user you should see a view cart button 
- [ ] As a user you should see a keep shopping button
