### ISSUE TITLE
Subtask: increment Navbar cart icon number

### ISSUE THREAD

**Issue by blydiet** [the-silver-snakesss/gracessshopper#31]
- [ ] As a user I should see the number zero near my cart If there is nothing in the cart
- [ ] As a user I should see the number increment when something is added to my cart 
- [ ] As a user, the number of friends brought should increment by one every time a new Item is added 
- [ ] As a user the cart number should decrement by one when an item is removed from my cart
