### ISSUE TITLE
Subtask: cart icon

### ISSUE THREAD

**Issue by blydiet** [the-silver-snakesss/gracessshopper#32]
#8
- [ ] As a user I should be able to see a cart Icon in the Navbar 
- [ ] As a user I should be able to see the number Of Items in my cart 
- [ ] As a user I should be able to see a table with a list Of friends name that I brought 
- [ ] As a user I should be able to see a table that also has the number of friends that I placed an order friend e.g. Quantity
- [ ] As a user I should be able to see on that table to delete a friend  that I no longer want 
- [ ] As a user I should see a price for all of my friends 
- [ ] As a user I should be able to see a total at the bottom of the table  that has the values for the price of friends and the number of friends that are about to be brought  
- [ ] As a user I should be able to see a checkout bottom
