### ISSUE TITLE
Subtask: home

### ISSUE THREAD

**Issue by blydiet** [the-silver-snakesss/gracessshopper#35]
#7
- [ ] As a user I should be able to see a Navbar with welcome and shop inside of the navbar 
- [ ] As a user Should be able to see text that says 'Welcome to Imagine Nation' 
- [ ] As a user I should be able to see Sign in button 
- [ ] As a user I should be able to see a Create Account button 
- [ ] As a user I should be able to click on both buttons
