### ISSUE TITLE
Subtask: Action/ Thunk for Cart Items

### ISSUE THREAD

**Issue by AsiaJoyG** [the-silver-snakesss/gracessshopper#37]
subtask of #6 

- [x] create action for viewing items in cart
- [x] create thunk for viewing items in cart
- [x] create case in ITEMS reducer for cart items
