### ISSUE TITLE
Subtask: User profile

### ISSUE THREAD

**Issue by blydiet** [the-silver-snakesss/gracessshopper#45]
- [ ] inside of the individual user file we should be able to see an order history in the navbar 
- [ ] inside of an individual user profile we should be to see the address 
- [ ] inside of an individual user profile we should be able to see the pay pal
